export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOG_OUT = 'LOG_OUT'
export const LOAD_PROFILE = 'LOAD_PROFILE'


export const HOME_VIDEO_SUCCESS = 'HOME_VIDEO_SUCCESS';
export const HOME_VIDEO_FAILURE = 'HOME_VIDEO_FAILURE';
export const HOME_VIDEO_REQUEST = 'HOME_VIDEO_REQUEST';


export const SELECTED_VIDEO_REQUEST = 'SELECTED_VIDEO_REQUEST';
export const SELECTED_VIDEO_SUCCESS = 'SELECTED_VIDEO_SUCCESS';
export const SELECTED_VIDEO_FAILURE = 'SELECTED_VIDEO_FAILURE';


export const CHANNEL_DETAIL_REQUEST = 'CHANNEL_DETAIL_REQUEST';
export const CHANNEL_DETAIL_SUCCESS = 'CHANNEL_DETAIL_SUCCESS';
export const CHANNEL_DETAIL_FAILS = 'CHANNEL_DETAIL_FAILS';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAILS = 'COMMENT_LIST_FAILS';


export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';


export const RELATED_VIDEO_REQUEST = 'RELATED_VIDEO_REQUEST';
export const RELATED_VIDEO_SUCCESS = 'RELATED_VIDEO_SUCCESS';
export const RELATED_VIDEO_FAILS = 'RELATED_VIDEO_FAILS';


export const SEARCH_VIDEO_REQUEST = 'SEARCH_VIDEO_REQUEST';
export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
export const SEARCH_VIDEO_FAILS = 'SEARCH_VIDEO_FAILS';

export const SUBSCRIPTION_VIDEO_REQUEST = 'SUBSCRIPTION_VIDEO_REQUEST';
export const SUBSCRIPTION_VIDEO_SUCCESS = 'SUBSCRIPTION_VIDEO_SUCCESS';
export const SUBSCRIPTION_VIDEO_FAILS = 'SUBSCRIPTION_VIDEO_FAILS';


export const CHANNEL_VIDEOS_REQUEST = 'CHANNEL_VIDEOS_REQUEST';
export const CHANNEL_VIDEOS_SUCCESS = 'CHANNEL_VIDEOS_SUCCESS';
export const CHANNEL_VIDEOS_FAILS = 'CHANNEL_VIDEOS_FAILS';


export const GET_SUBSCRIPTION_STATUS = 'GET_SUBSCRIPTION_STATUS';